import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, ArrowUpRight, Check, CheckCheck, ChevronDown, CircleAlert, Clock3, Download, Eye, FileJson, GitBranch, History, Layers2, Pause, Play, Printer, Radar, RotateCcw, ShieldCheck, SkipBack, SkipForward, Sparkles, SplitSquareHorizontal, Target, X } from 'lucide-react';
import { replay } from '../../sim-core/engine';
import type { SessionRecord, User } from '../../sim-core/types';
import { formatTime, humanize } from '../copy';
import { RadarMap } from '../tactical/RadarMap';
import { AiAnalysis } from './AiAnalysis';
import { ConfusionMatrix, ScoreRing, TrendChart } from '../components/Charts';
import { downloadJson, exportSessions } from '../lib/exports';

interface Props { sessions: SessionRecord[]; users: User[]; user: User; selectedId: string | null; onSelect: (id: string) => void; onPractice: () => void }
const METRIC_NAMES = { detection: 'Detection', classification: 'Classification', decision: 'Decision quality', outcome: 'Outcome', reasoning: 'Reasoning' };
export function AfterActionReview({ sessions, users, user, selectedId, onSelect, onPractice }: Props) {
  const own = sessions.filter(s => s.user_id === user.id && !s.synthetic);
  const available = sessions.filter(s => s.user_id === user.id || s.synthetic || user.role === 'instructor');
  const session = available.find(s => s.id === selectedId) ?? own[0] ?? available[0];
  const [cursor, setCursor] = useState(0);
  const [view, setView] = useState<'sensor' | 'truth' | 'split'>('sensor');
  const [playing, setPlaying] = useState(false);
  const [selectedTrack, setSelectedTrack] = useState<string | null>(null);
  const [tab, setTab] = useState<'debrief' | 'trends'>('debrief');
  const [speed, setSpeed] = useState(1);
  useEffect(() => {
    if (session) { setCursor(session.report.mistakes.find(m => m.severity === 'critical')?.tick ?? Math.min(session.end_tick, 80)); setSelectedTrack(session.report.actors[0]?.actor_id ?? null); }
    setPlaying(false); setView('sensor');
  }, [session?.id]);
  useEffect(() => {
    if (!playing || !session) return;
    const timer = setInterval(() => setCursor(t => { const next = Math.min(session.end_tick, t + speed); if (next === session.end_tick) setPlaying(false); return next; }), 250);
    return () => clearInterval(timer);
  }, [playing, session?.id, speed]);
  const full = useMemo(() => session ? replay(session.scenario, session.actions, session.end_tick) : null, [session?.id]);
  const frame = useMemo(() => session ? replay(session.scenario, session.actions.filter(a => a.tick <= cursor), Math.min(cursor, session.end_tick), false) : null, [session?.id, cursor]);
  if (!session || !frame || !full) return <><div className="page-heading"><div><div className="eyebrow">LEARNING STARTS WITH REFLECTION</div><h1>After-action review<span className="accent">.</span></h1></div></div><div className="panel empty-inline large-empty"><History size={35} /><p>Your first decision story starts here.</p><span>Complete an exercise to inspect its score, evidence, replay, and next learning opportunity.</span><button className="button primary" onClick={onPractice}>Start an exercise <ArrowRight size={14} /></button></div></>;
  const { report } = session;
  const operator = users.find(u => u.id === session.user_id)?.name ?? session.user_id;
  const actor = report.actors.find(a => a.actor_id === selectedTrack) ?? report.actors[0];
  const markers = full.events.filter(e => ['TrackAcknowledged', 'TrackClassified', 'ResponseOrdered', 'ResponseRejected'].includes(e.type));
  const trends = available.filter(s => s.user_id === session.user_id && s.synthetic === session.synthetic).sort((a, b) => a.started_at.localeCompare(b.started_at));
  const confusion = Array.from({ length: 3 }, (_, row) => Array.from({ length: 4 }, (_, col) => trends.reduce((sum, s) => sum + s.report.confusion_matrix[row][col], 0)));
  const verified = full.eventHash() === report.event_hash;
  const jump = (tick: number, actorId?: string | null) => { setCursor(Math.min(tick, session.end_tick)); setPlaying(false); if (actorId) setSelectedTrack(actorId); };
  const dateLabels = trends.map(s => new Date(s.started_at).toLocaleDateString('en-GB', { day: '2-digit', month: 'short' }));
  return <>
    <div className="page-heading"><div><div className="eyebrow">REPLAY. REFLECT. IMPROVE.</div><h1>Every decision tells a story<span className="accent">.</span></h1><p>Understand what you saw, what you decided, and what happened.</p></div><div className="heading-actions"><button className="button secondary" onClick={() => exportSessions([session], 'avlon-drishti-debrief.csv')}><Download size={14} />Export CSV</button><button className="button secondary icon-only" title="Print or save PDF" aria-label="Print or save PDF" onClick={() => window.print()}><Printer size={15} /></button><button className="button secondary icon-only" title="Export replay JSON" aria-label="Export replay JSON" onClick={() => downloadJson(`avlon-drishti-replay-${session.id}.json`, session)}><FileJson size={15} /></button></div></div>
    <div className="aar-selection"><div><span className="field-label">REVIEW SESSION</span><label className="select-wrap"><select aria-label="Review session" value={session.id} onChange={e => onSelect(e.target.value)}>{available.map(s => <option value={s.id} key={s.id}>{s.synthetic ? '[Example] ' : ''}{s.scenario.title} · {users.find(u => u.id === s.user_id)?.name ?? 'Operator'} · {s.report.total}/100</option>)}</select><ChevronDown size={12} /></label></div><div className="aar-selection-meta"><span>{operator}</span><span>{new Date(session.started_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}</span><span className={`tag ${report.provisional ? 'amber' : 'gray'}`}>{report.provisional ? 'PARTIAL SESSION' : 'COMPLETE'}</span>{session.synthetic && <span className="tag amber">SYNTHETIC EXAMPLE</span>}</div></div>
    <div className="aar-tabs"><button className={tab === 'debrief' ? 'active' : ''} onClick={() => setTab('debrief')}><History size={14} />Session debrief</button><button className={tab === 'trends' ? 'active' : ''} onClick={() => setTab('trends')}><Target size={14} />Individual trends<span className="count-pill">{trends.length}</span></button></div>
    {tab === 'debrief' ? <>
      <section className="score-summary panel"><div className="overall-score"><ScoreRing value={report.total} size={130} /><div><span className="eyebrow">{report.provisional ? 'PROVISIONAL RESULT' : 'EXERCISE RESULT'}</span><h2>{report.grade}</h2><p>{report.provisional ? `${Math.round(report.completion * 100)}% of the exercise elapsed. This is a partial review.` : report.total >= 75 ? 'A strong foundation. Find your next edge.' : 'Make the next decision better than the last.'}</p><span className="score-summary-meta"><Clock3 size={12} />{formatTime(report.duration_s)} reviewed <span>·</span><GitBranch size={12} />{report.actors.length} decision paths</span></div></div><div className="score-metrics">{Object.entries(report.metrics).map(([key, value]) => <div key={key}><span>{METRIC_NAMES[key as keyof typeof METRIC_NAMES]}</span><div><i style={{ width: `${value}%` }} /></div><strong>{value}<small>/100</small></strong></div>)}</div></section>
      <section className="panel replay-panel"><div className="panel-header"><div className="panel-title"><History size={17} /><h2>Reconstruct the moment</h2><span className={`tag ${verified ? '' : 'red'}`}>{verified ? <CheckCheck size={10} /> : <CircleAlert size={10} />}{verified ? 'REPLAY VERIFIED' : 'CHECKSUM MISMATCH'}</span></div><div className="replay-view-toggle" role="group" aria-label="Replay perspective"><button aria-pressed={view === 'sensor'} className={view === 'sensor' ? 'active' : ''} onClick={() => setView('sensor')}><Radar size={12} />Trainee view</button><button aria-pressed={view === 'truth'} className={view === 'truth' ? 'active' : ''} onClick={() => setView('truth')}><Eye size={12} />Ground truth</button><button aria-pressed={view === 'split'} className={view === 'split' ? 'active' : ''} onClick={() => setView('split')} title="Compare both views" aria-label="Compare both views"><SplitSquareHorizontal size={14} /></button></div></div>
        <div className={`replay-map-grid ${view === 'split' ? 'split' : ''}`}><RadarMap scenario={session.scenario} contacts={frame.contacts(view === 'truth')} selected={selectedTrack} onSelect={setSelectedTrack} truth={view === 'truth'} sweep={false} compact={view === 'split'} />{view === 'split' && <RadarMap scenario={session.scenario} contacts={frame.contacts(true)} selected={selectedTrack} onSelect={setSelectedTrack} truth sweep={false} compact />}</div>
        <div className="replay-context"><Eye size={13} /><span>{view === 'sensor' ? 'Only observations and classifications available to the trainee at this exact moment.' : view === 'truth' ? 'Hidden exercise truth: actual positions and allegiances at the same simulation tick.' : 'Same seed. Same tick. Two perspectives: the trainee’s evidence and the hidden truth.'}</span><code>{report.event_hash}</code></div>
        <div className="timeline"><div className="timeline-time"><span>{formatTime(cursor / 4)}<small> / {formatTime(session.end_tick / 4)}</small></span><div><span className="timeline-key good" />Decision<span className="timeline-key bad" />Mistake</div></div><div className="timeline-track"><input aria-label="Replay timeline" type="range" min="0" max={Math.max(1, session.end_tick)} step="1" value={cursor} onChange={e => { setCursor(Number(e.target.value)); setPlaying(false); }} /><div className="timeline-markers">{markers.map(e => <button key={e.seq} className={e.type === 'ResponseRejected' || e.type === 'TrackClassified' && !e.payload.correct ? 'bad' : 'good'} style={{ left: `${e.tick / Math.max(1, session.end_tick) * 100}%` }} title={`${formatTime(e.tick / 4)} · ${humanize(e.type)} · ${e.actor_id}`} aria-label={`Jump to ${e.type} at ${formatTime(e.tick / 4)}`} onClick={() => jump(e.tick, e.actor_id)} />)}</div></div><div className="timeline-controls"><div><button className="icon-button" title="Restart replay" aria-label="Restart replay" onClick={() => jump(0)}><RotateCcw size={15} /></button><button className="icon-button" aria-label="Previous decision" disabled={!markers.length} onClick={() => jump([...markers].reverse().find(m => m.tick < cursor)?.tick ?? 0)}><SkipBack size={15} /></button><button className="play-control" aria-label={playing ? 'Pause replay' : 'Play replay'} onClick={() => { if (cursor >= session.end_tick) setCursor(0); setPlaying(v => !v); }}>{playing ? <Pause size={15} /> : <Play size={15} />}</button><button className="icon-button" aria-label="Next decision" disabled={!markers.length} onClick={() => jump(markers.find(m => m.tick > cursor)?.tick ?? session.end_tick)}><SkipForward size={15} /></button><select aria-label="Replay speed" value={speed} onChange={e => setSpeed(Number(e.target.value))}><option value="1">1×</option><option value="4">4×</option><option value="8">8×</option></select></div><span className="mono muted">TICK {cursor} · FIXED STEP 250 ms · SEED {session.scenario.seed}</span></div></div>
      </section>
      <AiAnalysis record={session} history={trends} onPractice={onPractice} />
      <div className="debrief-grid"><section className="panel"><div className="panel-header"><div className="panel-title"><GitBranch size={16} /><h2>Decision-tree trace</h2></div>{actor && <select className="compact-select" aria-label="Decision tree contact" value={actor.actor_id} onChange={e => setSelectedTrack(e.target.value)}>{report.actors.map(a => <option key={a.actor_id} value={a.actor_id}>{a.label} · {a.score}/100</option>)}</select>}</div><div className="panel-content">{actor ? <><div className="decision-tree">{actor.nodes.map((node, index) => <div className={`tree-node ${node.passed ? 'passed' : 'failed'}`} key={node.name}><div className="tree-connector" /><span className="tree-check">{node.passed ? <Check size={12} /> : <X size={12} />}</span><div><strong><span>{String(index + 1).padStart(2, '0')}</span>{node.name}</strong><p>{node.detail}</p></div><span className="tree-points">{node.points > 0 ? `+${node.points}` : '—'}</span></div>)}</div><div className="ideal-path"><span>REFERENCE PATH</span><p>{actor.ideal_path.join(' → ')}</p></div></> : <div className="empty-inline"><p>No contacts were yet detectable.</p></div>}</div></section>
        <section className="panel"><div className="panel-header"><div className="panel-title"><CircleAlert size={16} /><h2>Learning moments</h2><span className="count-pill">{report.mistakes.length}</span></div><span className="mono muted">CLICK TO REPLAY</span></div><div className="mistake-list">{report.mistakes.map((m, i) => <button className={`mistake-item ${m.severity}`} key={i} onClick={() => jump(m.tick, m.actor_id)}><span className="mistake-time">{formatTime(m.tick / 4)}<span className={`tag ${m.severity === 'critical' ? 'red' : m.severity === 'warning' ? 'amber' : 'gray'}`}>{m.category.toUpperCase()}</span></span><strong>{m.message}</strong><p>{m.recommendation}</p><span className="mistake-jump">Replay this moment <ArrowUpRight size={11} /></span></button>)}{!report.mistakes.length && <div className="empty-inline large-empty"><ShieldCheck size={30} /><p>Every recorded decision aligned.</p><span>Increase the difficulty to find the next learning opportunity.</span></div>}</div></section>
      </div>
      <div className="next-learning-banner"><Sparkles size={22} /><div><h3>The debrief is only the beginning.</h3><p>Turn this session’s evidence into a more focused next exercise.</p></div><button className="button primary" onClick={onPractice}>Find my next challenge <ArrowRight size={14} /></button></div>
    </> : <>
      <div className="trend-heading"><h3>{operator}’s learning trajectory</h3><span className="tag gray">{trends.length} {session.synthetic ? 'SYNTHETIC ' : ''}SESSIONS</span></div>
      <div className="trend-grid"><section className="panel"><div className="panel-header"><div className="panel-title"><Target size={16} /><h2>Score over time</h2></div><span className="mono muted">0–100 POINTS</span></div><div className="panel-content"><TrendChart values={trends.map(s => s.report.total)} labels={dateLabels} /></div></section><section className="panel"><div className="panel-header"><div className="panel-title"><Clock3 size={16} /><h2>Time to acknowledgement</h2></div><span className="mono muted">LOWER IS BETTER</span></div><div className="panel-content"><TrendChart values={trends.filter(s => s.report.detection_mean_s !== null).map(s => s.report.detection_mean_s!)} labels={trends.filter(s => s.report.detection_mean_s !== null).map(s => new Date(s.started_at).toLocaleDateString('en-GB', { day: '2-digit', month: 'short' }))} max={Math.max(15, ...trends.map(s => s.report.detection_mean_s ?? 0))} color="#dcb077" suffix="s" /></div></section></div>
      <div className="debrief-grid"><section className="panel"><div className="panel-header"><h2>Classification confusion matrix</h2><span className="mono muted">ALL SELECTED TRAINEE SESSIONS</span></div><div className="panel-content"><ConfusionMatrix matrix={confusion} /></div></section><section className="panel"><div className="panel-header"><h2>Context × contact-load heatmap</h2></div><div className="panel-content table-scroll"><table className="heatmap-table"><thead><tr><th scope="col">Time of day</th><th scope="col">1 hostile</th><th scope="col">2–4 hostiles</th><th scope="col">5+ hostiles</th></tr></thead><tbody>{(['day', 'dusk', 'night'] as const).map(time => <tr key={time}><th scope="row">{humanize(time)}</th>{[0, 1, 2].map(bucket => { const matched = trends.filter(s => { const count = s.scenario.actors.filter(a => a.allegiance === 'hostile').reduce((n, a) => n + a.count, 0); return s.scenario.environment.time_of_day === time && (count <= 1 ? 0 : count <= 4 ? 1 : 2) === bucket; }); const value = matched.length ? Math.round(matched.reduce((n, s) => n + s.report.total, 0) / matched.length) : null; return <td key={bucket} className={value === null ? '' : value >= 75 ? 'good' : 'weak'}>{value ?? '—'}<small>{matched.length ? `${matched.length} runs` : 'No evidence'}</small></td>; })}</tr>)}</tbody></table><p className="fine-print">Mean observed score, not a validated readiness rating. Partial sessions are marked in the register.</p></div></section></div>
      <section className="panel session-register"><div className="panel-header"><h2>Session register</h2><button className="button ghost small" disabled={!trends.length} title={trends.length ? 'Export trend data' : 'No trend data to export'} onClick={() => exportSessions(trends)}><Download size={12} />Export trend data</button></div><div className="table-scroll"><table className="data-table"><thead><tr><th>EXERCISE</th><th>DATE</th><th>SCORE</th><th>DETECTION</th><th>CLASSIFICATION</th><th>DECISION</th><th /></tr></thead><tbody>{trends.map(s => <tr key={s.id}><td>{s.scenario.title}{s.report.provisional && <span className="inline-partial">Partial</span>}</td><td>{new Date(s.started_at).toLocaleDateString('en-GB')}</td><td className="text-amber">{s.report.total}</td><td>{s.report.metrics.detection}%</td><td>{s.report.metrics.classification}%</td><td>{s.report.metrics.decision}%</td><td><button className="icon-button" aria-label={`Review ${s.scenario.title}`} onClick={() => { onSelect(s.id); setTab('debrief'); }}><ArrowUpRight size={14} /></button></td></tr>)}</tbody></table></div></section>
    </>}
  </>;
}
